package eniso;


/**
* eniso/CalcHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Monday, November 24, 2025 1:03:51 PM CET
*/

abstract public class CalcHelper
{
  private static String  _id = "IDL:eniso/Calc:1.0";

  public static void insert (org.omg.CORBA.Any a, eniso.Calc that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static eniso.Calc extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (eniso.CalcHelper.id (), "Calc");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static eniso.Calc read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalcStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, eniso.Calc value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static eniso.Calc narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof eniso.Calc)
      return (eniso.Calc)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      eniso._CalcStub stub = new eniso._CalcStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static eniso.Calc unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof eniso.Calc)
      return (eniso.Calc)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      eniso._CalcStub stub = new eniso._CalcStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
