package eniso;


/**
* eniso/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Monday, November 24, 2025 1:03:51 PM CET
*/

public interface CalcOperations 
{
  long div (long a, long b) throws eniso.DivByZeroException;
} // interface CalcOperations
