package eniso;

/**
* eniso/CalcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Monday, November 24, 2025 1:03:51 PM CET
*/

public final class CalcHolder implements org.omg.CORBA.portable.Streamable
{
  public eniso.Calc value = null;

  public CalcHolder ()
  {
  }

  public CalcHolder (eniso.Calc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = eniso.CalcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    eniso.CalcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return eniso.CalcHelper.type ();
  }

}
