package eniso;


/**
* eniso/Calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Monday, November 24, 2025 1:03:51 PM CET
*/

public interface Calc extends CalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calc
