package eniso;


/**
* eniso/DivByZeroException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Monday, November 24, 2025 1:03:51 PM CET
*/

public final class DivByZeroException extends org.omg.CORBA.UserException
{
  public String message = null;

  public DivByZeroException ()
  {
    super(DivByZeroExceptionHelper.id());
  } // ctor

  public DivByZeroException (String _message)
  {
    super(DivByZeroExceptionHelper.id());
    message = _message;
  } // ctor


  public DivByZeroException (String $reason, String _message)
  {
    super(DivByZeroExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class DivByZeroException
