package BomberManCorba;


/**
* BomberManCorba/_ClientCorbaStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/


// Interface for ClientCorba - services provided by the client (called by server)
public class _ClientCorbaStub extends org.omg.CORBA.portable.ObjectImpl implements BomberManCorba.ClientCorba
{


  // Called by server to notify client of model changes
  public void modelChanged (BomberManCorba.DynamicGameModel model)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modelChanged", true);
                BomberManCorba.DynamicGameModelHelper.write ($out, model);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                modelChanged (model        );
            } finally {
                _releaseReply ($in);
            }
  } // modelChanged

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BomberManCorba/ClientCorba:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "BomberManCorba._ClientCorbaStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ClientCorbaStub
