package BomberManCorba;

/**
* BomberManCorba/ClientCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/


// Interface for ClientCorba - services provided by the client (called by server)
public final class ClientCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public BomberManCorba.ClientCorba value = null;

  public ClientCorbaHolder ()
  {
  }

  public ClientCorbaHolder (BomberManCorba.ClientCorba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BomberManCorba.ClientCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BomberManCorba.ClientCorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BomberManCorba.ClientCorbaHelper.type ();
  }

}
