package BomberManCorba;


/**
* BomberManCorba/ClientCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/


// Interface for ClientCorba - services provided by the client (called by server)
public interface ClientCorbaOperations 
{

  // Called by server to notify client of model changes
  void modelChanged (BomberManCorba.DynamicGameModel model);
} // interface ClientCorbaOperations
