package BomberManCorba;


/**
* BomberManCorba/ClientCorbaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/


// Interface for ClientCorba - services provided by the client (called by server)
abstract public class ClientCorbaHelper
{
  private static String  _id = "IDL:BomberManCorba/ClientCorba:1.0";

  public static void insert (org.omg.CORBA.Any a, BomberManCorba.ClientCorba that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BomberManCorba.ClientCorba extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BomberManCorba.ClientCorbaHelper.id (), "ClientCorba");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BomberManCorba.ClientCorba read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientCorbaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BomberManCorba.ClientCorba value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BomberManCorba.ClientCorba narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BomberManCorba.ClientCorba)
      return (BomberManCorba.ClientCorba)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BomberManCorba._ClientCorbaStub stub = new BomberManCorba._ClientCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BomberManCorba.ClientCorba unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BomberManCorba.ClientCorba)
      return (BomberManCorba.ClientCorba)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BomberManCorba._ClientCorbaStub stub = new BomberManCorba._ClientCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
