package BomberManCorba;


/**
* BomberManCorba/ClientCorbaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/


// Interface for ClientCorba - services provided by the client (called by server)
public abstract class ClientCorbaPOA extends org.omg.PortableServer.Servant
 implements BomberManCorba.ClientCorbaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("modelChanged", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Called by server to notify client of model changes
       case 0:  // BomberManCorba/ClientCorba/modelChanged
       {
         BomberManCorba.DynamicGameModel model = BomberManCorba.DynamicGameModelHelper.read (in);
         this.modelChanged (model);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BomberManCorba/ClientCorba:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientCorba _this() 
  {
    return ClientCorbaHelper.narrow(
    super._this_object());
  }

  public ClientCorba _this(org.omg.CORBA.ORB orb) 
  {
    return ClientCorbaHelper.narrow(
    super._this_object(orb));
  }


} // class ClientCorbaPOA
