package BomberManCorba;


/**
* BomberManCorba/DynamicGameModelHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/

abstract public class DynamicGameModelHelper
{
  private static String  _id = "IDL:BomberManCorba/DynamicGameModel:1.0";

  public static void insert (org.omg.CORBA.Any a, BomberManCorba.DynamicGameModel that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BomberManCorba.DynamicGameModel extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "frame",
            _tcOf_members0,
            null);
          _tcOf_members0 = BomberManCorba.SpriteDataHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (BomberManCorba.SpriteListHelper.id (), "SpriteList", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "sprites",
            _tcOf_members0,
            null);
          _tcOf_members0 = BomberManCorba.PlayerDataHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (BomberManCorba.PlayerListHelper.id (), "PlayerList", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "players",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (BomberManCorba.DynamicGameModelHelper.id (), "DynamicGameModel", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BomberManCorba.DynamicGameModel read (org.omg.CORBA.portable.InputStream istream)
  {
    BomberManCorba.DynamicGameModel value = new BomberManCorba.DynamicGameModel ();
    value.frame = istream.read_longlong ();
    value.sprites = BomberManCorba.SpriteListHelper.read (istream);
    value.players = BomberManCorba.PlayerListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BomberManCorba.DynamicGameModel value)
  {
    ostream.write_longlong (value.frame);
    BomberManCorba.SpriteListHelper.write (ostream, value.sprites);
    BomberManCorba.PlayerListHelper.write (ostream, value.players);
  }

}
