package BomberManCorba;


/**
* BomberManCorba/DynamicGameModel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/

public final class DynamicGameModel implements org.omg.CORBA.portable.IDLEntity
{
  public long frame = (long)0;
  public BomberManCorba.SpriteData sprites[] = null;
  public BomberManCorba.PlayerData players[] = null;

  public DynamicGameModel ()
  {
  } // ctor

  public DynamicGameModel (long _frame, BomberManCorba.SpriteData[] _sprites, BomberManCorba.PlayerData[] _players)
  {
    frame = _frame;
    sprites = _sprites;
    players = _players;
  } // ctor

} // class DynamicGameModel
