package BomberManCorba;


/**
* BomberManCorba/MazeRowHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/


// Structure to represent the maze (2D array will be sent as sequence)
public final class MazeRowHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public MazeRowHolder ()
  {
  }

  public MazeRowHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BomberManCorba.MazeRowHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BomberManCorba.MazeRowHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BomberManCorba.MazeRowHelper.type ();
  }

}
