package BomberManCorba;

/**
* BomberManCorba/PlayerDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/

public final class PlayerDataHolder implements org.omg.CORBA.portable.Streamable
{
  public BomberManCorba.PlayerData value = null;

  public PlayerDataHolder ()
  {
  }

  public PlayerDataHolder (BomberManCorba.PlayerData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BomberManCorba.PlayerDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BomberManCorba.PlayerDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BomberManCorba.PlayerDataHelper.type ();
  }

}
