package BomberManCorba;


/**
* BomberManCorba/PlayerData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/

public final class PlayerData implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String name = null;
  public int score = (int)0;
  public boolean alive = false;

  public PlayerData ()
  {
  } // ctor

  public PlayerData (int _id, String _name, int _score, boolean _alive)
  {
    id = _id;
    name = _name;
    score = _score;
    alive = _alive;
  } // ctor

} // class PlayerData
