package BomberManCorba;


/**
* BomberManCorba/PlayerListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/

public final class PlayerListHolder implements org.omg.CORBA.portable.Streamable
{
  public BomberManCorba.PlayerData value[] = null;

  public PlayerListHolder ()
  {
  }

  public PlayerListHolder (BomberManCorba.PlayerData[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BomberManCorba.PlayerListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BomberManCorba.PlayerListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BomberManCorba.PlayerListHelper.type ();
  }

}
