package BomberManCorba;


/**
* BomberManCorba/ServerCorbaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/


// Interface for ServerCorba - services provided by the server (called by client)
abstract public class ServerCorbaHelper
{
  private static String  _id = "IDL:BomberManCorba/ServerCorba:1.0";

  public static void insert (org.omg.CORBA.Any a, BomberManCorba.ServerCorba that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BomberManCorba.ServerCorba extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BomberManCorba.ServerCorbaHelper.id (), "ServerCorba");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BomberManCorba.ServerCorba read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerCorbaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BomberManCorba.ServerCorba value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BomberManCorba.ServerCorba narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BomberManCorba.ServerCorba)
      return (BomberManCorba.ServerCorba)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BomberManCorba._ServerCorbaStub stub = new BomberManCorba._ServerCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BomberManCorba.ServerCorba unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BomberManCorba.ServerCorba)
      return (BomberManCorba.ServerCorba)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BomberManCorba._ServerCorbaStub stub = new BomberManCorba._ServerCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
