package BomberManCorba;


/**
* BomberManCorba/ServerCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/


// Interface for ServerCorba - services provided by the server (called by client)
public interface ServerCorba extends ServerCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerCorba
