package BomberManCorba;

/**
* BomberManCorba/ServerCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/


// Interface for ServerCorba - services provided by the server (called by client)
public final class ServerCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public BomberManCorba.ServerCorba value = null;

  public ServerCorbaHolder ()
  {
  }

  public ServerCorbaHolder (BomberManCorba.ServerCorba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BomberManCorba.ServerCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BomberManCorba.ServerCorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BomberManCorba.ServerCorbaHelper.type ();
  }

}
