package BomberManCorba;


/**
* BomberManCorba/ServerCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/


// Interface for ServerCorba - services provided by the server (called by client)
public interface ServerCorbaOperations 
{

  // Connect a player to the game
  BomberManCorba.StartGameInfo connect (String playerName, BomberManCorba.ClientCorba client);

  // Movement methods
  void moveLeft (int playerId);
  void moveRight (int playerId);
  void moveUp (int playerId);
  void moveDown (int playerId);

  // Action methods
  void releaseBomb (int playerId);
} // interface ServerCorbaOperations
