package BomberManCorba;


/**
* BomberManCorba/SpriteListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/

public final class SpriteListHolder implements org.omg.CORBA.portable.Streamable
{
  public BomberManCorba.SpriteData value[] = null;

  public SpriteListHolder ()
  {
  }

  public SpriteListHolder (BomberManCorba.SpriteData[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BomberManCorba.SpriteListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BomberManCorba.SpriteListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BomberManCorba.SpriteListHelper.type ();
  }

}
