package BomberManCorba;


/**
* BomberManCorba/SpriteListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/

abstract public class SpriteListHelper
{
  private static String  _id = "IDL:BomberManCorba/SpriteList:1.0";

  public static void insert (org.omg.CORBA.Any a, BomberManCorba.SpriteData[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BomberManCorba.SpriteData[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = BomberManCorba.SpriteDataHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (BomberManCorba.SpriteListHelper.id (), "SpriteList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BomberManCorba.SpriteData[] read (org.omg.CORBA.portable.InputStream istream)
  {
    BomberManCorba.SpriteData value[] = null;
    int _len0 = istream.read_long ();
    value = new BomberManCorba.SpriteData[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = BomberManCorba.SpriteDataHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BomberManCorba.SpriteData[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      BomberManCorba.SpriteDataHelper.write (ostream, value[_i0]);
  }

}
