package BomberManCorba;

/**
* BomberManCorba/SpriteDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/

public final class SpriteDataHolder implements org.omg.CORBA.portable.Streamable
{
  public BomberManCorba.SpriteData value = null;

  public SpriteDataHolder ()
  {
  }

  public SpriteDataHolder (BomberManCorba.SpriteData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BomberManCorba.SpriteDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BomberManCorba.SpriteDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BomberManCorba.SpriteDataHelper.type ();
  }

}
