package BomberManCorba;


/**
* BomberManCorba/SpriteData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/

public final class SpriteData implements org.omg.CORBA.portable.IDLEntity
{
  public String type = null;
  public double x = (double)0;
  public double y = (double)0;
  public int id = (int)0;

  public SpriteData ()
  {
  } // ctor

  public SpriteData (String _type, double _x, double _y, int _id)
  {
    type = _type;
    x = _x;
    y = _y;
    id = _id;
  } // ctor

} // class SpriteData
