package BomberManCorba;


/**
* BomberManCorba/StartGameInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/

public final class StartGameInfo implements org.omg.CORBA.portable.IDLEntity
{
  public int playerId = (int)0;
  public int maze[][] = null;

  public StartGameInfo ()
  {
  } // ctor

  public StartGameInfo (int _playerId, int[][] _maze)
  {
    playerId = _playerId;
    maze = _maze;
  } // ctor

} // class StartGameInfo
