package BomberManCorba;


/**
* BomberManCorba/StartGameInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/

abstract public class StartGameInfoHelper
{
  private static String  _id = "IDL:BomberManCorba/StartGameInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, BomberManCorba.StartGameInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BomberManCorba.StartGameInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "playerId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (BomberManCorba.MazeRowHelper.id (), "MazeRow", _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (BomberManCorba.MazeHelper.id (), "Maze", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "maze",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (BomberManCorba.StartGameInfoHelper.id (), "StartGameInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BomberManCorba.StartGameInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    BomberManCorba.StartGameInfo value = new BomberManCorba.StartGameInfo ();
    value.playerId = istream.read_long ();
    value.maze = BomberManCorba.MazeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BomberManCorba.StartGameInfo value)
  {
    ostream.write_long (value.playerId);
    BomberManCorba.MazeHelper.write (ostream, value.maze);
  }

}
