package BomberManCorba;

/**
* BomberManCorba/StartGameInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../idl/BomberMan.idl
* Monday, November 24, 2025 8:10:47 PM CET
*/

public final class StartGameInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public BomberManCorba.StartGameInfo value = null;

  public StartGameInfoHolder ()
  {
  }

  public StartGameInfoHolder (BomberManCorba.StartGameInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BomberManCorba.StartGameInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BomberManCorba.StartGameInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BomberManCorba.StartGameInfoHelper.type ();
  }

}
